# -*- coding: utf-8 -*-
"""Copy of multiple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YC3sKyIPKLLLSlIHvBfR4EPAThZ4Moa

# Multiple Linear Regression

## Importing the libraries
"""

import numpy as np
import pandas as pd
import pickle

"""## Importing the dataset"""

dataset = pd.read_csv('./insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X[0:10,:])
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

X[:,5] = (X[:,5] == 'male').astype(int) 
X[:,-1] = (X[:,-1] == 'yes').astype(int)

print(X[0:10,:])
"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the Random Forest model on the Training set"""

from sklearn.ensemble import RandomForestRegressor
regressor2 = RandomForestRegressor(n_estimators = 10 ,random_state=0)
regressor2.fit(X, y)

"""## Predicting the Test set results"""

y_pred2 = regressor2.predict(X_test)
np.set_printoptions(precision=2)
# print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test.reshape(len(y_test),1)),1))

"""## Evaluating the Model Performance"""

from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred2))

pickle.dump(regressor2,open('model.pkl','wb'))
